export type Layer = "camera" | "edge" | "stream" | "cloud" | "storage" | "control";

export type TechSpec = {
  id: string;
  name: string;
  tech: string;
  layer: Layer;
  receives: string;
  does: string;
  outputs: string;
  why: string;
  simple: string;
  technical: string;
};

export const LAYER_META: Record<Layer, { label: string; color: string }> = {
  camera: { label: "Camera layer", color: "var(--muted)" },
  edge: { label: "Edge AI (near intersection)", color: "var(--edge)" },
  stream: { label: "Streaming layer", color: "var(--success)" },
  cloud: { label: "MAARG cloud", color: "var(--primary)" },
  storage: { label: "Storage layer", color: "var(--primary)" },
  control: { label: "Signal control", color: "var(--success)" },
};

export const TECH: Record<string, TechSpec> = {
  camera: {
    id: "camera",
    name: "CCTV / ANPR Camera",
    tech: "IP camera · RTSP/H.264",
    layer: "camera",
    receives: "Light from the road scene",
    does: "Captures continuous video of the approach lanes (typically 25 fps).",
    outputs: "Raw video stream (RTSP) to the local edge server",
    why: "It is the only sensor that sees vehicle type, plate, lane and movement at the same time.",
    simple: "The camera watches the road and records video, like an eye on a pole.",
    technical:
      "An IP camera encodes frames (H.264/H.265) and exposes an RTSP stream over the local network to the edge node. Camera ID, lane polygons and GPS position are pre-configured metadata.",
  },
  frames: {
    id: "frames",
    name: "Frame Extraction",
    tech: "OpenCV · Python",
    layer: "edge",
    receives: "RTSP video stream from CAM_07",
    does: "Decodes the stream and samples frames at a fixed rate, attaching camera timestamps.",
    outputs: "Timestamped frames (e.g. frame #182 @ 08:42:16.120)",
    why: "AI models work on individual images, not on encoded video.",
    simple: "The video is cut into individual pictures.",
    technical:
      "cv2.VideoCapture decodes the RTSP stream; frames are sampled (e.g. every frame or every Nth frame) and stamped with a monotonic clock synchronised via NTP.",
  },
  preprocess: {
    id: "preprocess",
    name: "Preprocessing",
    tech: "OpenCV · NumPy",
    layer: "edge",
    receives: "Raw decoded frames",
    does: "Resizes, normalises, masks the region of interest and adjusts for low light / glare.",
    outputs: "Model-ready tensors (e.g. 640×640, normalised)",
    why: "Consistent input improves detection accuracy and speed.",
    simple: "Each picture is cleaned up and cropped to the road area.",
    technical:
      "Letterbox resize to the detector input size, colour conversion BGR→RGB, ROI mask for lanes, optional CLAHE for night frames, then conversion to a normalised tensor.",
  },
  yolo: {
    id: "yolo",
    name: "Vehicle Detection",
    tech: "YOLO · PyTorch",
    layer: "edge",
    receives: "Preprocessed frame tensor",
    does: "Finds every vehicle in the frame and classifies it (car, bus, truck, bike, auto, emergency).",
    outputs: "Bounding boxes + class + confidence per vehicle",
    why: "Every later step depends on knowing where vehicles are.",
    simple: "The AI draws a box around every vehicle and says what it is.",
    technical:
      "A YOLO object detector (PyTorch, optionally exported to TensorRT/ONNX on the edge GPU) returns [x1,y1,x2,y2, class, score]; non-max suppression removes duplicate boxes.",
  },
  bytetrack: {
    id: "bytetrack",
    name: "Multi-Object Tracking",
    tech: "ByteTrack",
    layer: "edge",
    receives: "Per-frame detections",
    does: "Links detections across frames so each vehicle keeps a stable local track ID.",
    outputs: "Track ID, path in image, lane, direction, pixel speed",
    why: "Without tracking, the same car would be counted 25 times every second.",
    simple: "It follows each vehicle from picture to picture so it is counted only once.",
    technical:
      "ByteTrack associates high- and low-confidence detections to existing tracks using IoU matching and a Kalman motion model. Track history gives lane, heading and an approximate speed via a calibrated pixel-to-metre homography.",
  },
  plate: {
    id: "plate",
    name: "License Plate Detection",
    tech: "YOLO (plate model)",
    layer: "edge",
    receives: "Vehicle crops from tracked boxes",
    does: "Locates the number plate region inside each vehicle crop.",
    outputs: "Plate crop image + location",
    why: "OCR is far more accurate on a tight plate crop than on the full frame.",
    simple: "It finds the number plate on each vehicle.",
    technical:
      "A second lightweight detector runs on vehicle crops; the best-quality crop across a track (sharpest, most frontal) is selected for OCR.",
  },
  ocr: {
    id: "ocr",
    name: "Plate OCR",
    tech: "PaddleOCR",
    layer: "edge",
    receives: "Plate crop",
    does: "Reads the characters on the plate and validates the format.",
    outputs: "Plate text + OCR confidence (e.g. DL01AB1234, 0.96)",
    why: "The plate is the strongest key for linking the same vehicle across cameras.",
    simple: "It reads the number written on the plate.",
    technical:
      "PaddleOCR text recognition on the plate crop; results are checked against Indian plate regex patterns and fused across several frames of the same track to raise confidence.",
  },
  observation: {
    id: "observation",
    name: "Observation Generation",
    tech: "Python service",
    layer: "edge",
    receives: "Track + class + plate + camera metadata",
    does: "Packages one compact event per vehicle passage.",
    outputs: "Structured observation (~0.5 KB JSON)",
    why: "This is what turns megabytes of video into a small, meaningful traffic event.",
    simple: "Everything learned about the vehicle is written down as one short record.",
    technical:
      "When a track crosses the virtual count line, a schema-validated observation is created with camera_id, timestamp, track/vehicle ID, plate, type, lane, direction, speed, GPS and confidence, then produced to Kafka.",
  },
  kafka: {
    id: "kafka",
    name: "Real-time Event Bus",
    tech: "Apache Kafka",
    layer: "stream",
    receives: "Observations from every edge node",
    does: "Durably queues events in topics/partitions and delivers them to cloud consumers.",
    outputs: "Ordered observation stream (topic: maarg.observations)",
    why: "Thousands of cameras can publish continuously without overloading cloud services.",
    simple: "A high-speed conveyor belt that carries every observation to the central system.",
    technical:
      "Edge producers publish to a partitioned topic keyed by camera/junction; consumer groups for ingestion, analytics and alerts read independently. Retention allows replay after failures.",
  },
  ingestion: {
    id: "ingestion",
    name: "Event Ingestion",
    tech: "Python consumers",
    layer: "cloud",
    receives: "Observation stream from Kafka",
    does: "Validates schema, de-duplicates, enriches with junction/road metadata.",
    outputs: "Clean, enriched observations",
    why: "Bad or duplicate events would corrupt counts and predictions.",
    simple: "Checks every record is correct before it is used.",
    technical:
      "Consumer group reads maarg.observations, validates against the schema, drops duplicates by (camera_id, track_id), joins camera → road-segment metadata and fans out to storage and stream processors.",
  },
  processing: {
    id: "processing",
    name: "Observation Processing",
    tech: "Python stream processors",
    layer: "cloud",
    receives: "Clean observations",
    does: "Normalises units, fills camera context, flags low-confidence reads and routes events to the right engines.",
    outputs: "Routed events for association, analytics and alerts",
    why: "Each downstream engine needs the observation in a consistent form.",
    simple: "Sorts every record and sends it to the right department.",
    technical: "Stateless processors map camera-local fields to city-level identifiers (segment, approach, movement) and attach quality flags (e.g. OCR confidence < 0.8).",
  },
  historical: {
    id: "historical",
    name: "Historical Analysis",
    tech: "TimescaleDB aggregates",
    layer: "cloud",
    receives: "Months of time-bucketed flows",
    does: "Builds typical profiles per junction, weekday and time of day.",
    outputs: "Expected baseline (e.g. Tue 08:45 J-04 N ≈ 36 veh/min)",
    why: "Predictions are more reliable when live data is compared with what normally happens.",
    simple: "Remembers what traffic usually looks like at this time.",
    technical: "Continuous aggregates produce per-approach profiles; live deviations from the baseline indicate incidents or unusual demand.",
  },
  redis: {
    id: "redis",
    name: "Live State Cache",
    tech: "Redis",
    layer: "storage",
    receives: "Latest counts, queues and signal states",
    does: "Holds the current city state in memory for millisecond reads.",
    outputs: "Fast current state (e.g. J-04 queue = 23)",
    why: "Signal decisions need the current state instantly.",
    simple: "Fast current state.",
    technical:
      "Key/value and sorted-set structures hold per-junction counters, rolling windows and active corridor state with TTLs.",
  },
  mongodb: {
    id: "mongodb",
    name: "Observation Store",
    tech: "MongoDB",
    layer: "storage",
    receives: "Every enriched observation",
    does: "Stores vehicle observations and metadata as documents.",
    outputs: "Queryable observation history per vehicle / camera",
    why: "Flexible documents fit observations with optional fields (plate unread, etc.).",
    simple: "Vehicle observations and metadata.",
    technical:
      "Documents indexed on plate, camera_id and timestamp support journey lookup and audit queries.",
  },
  timescale: {
    id: "timescale",
    name: "Time-series Store",
    tech: "TimescaleDB",
    layer: "storage",
    receives: "Aggregated flows (per lane, per minute)",
    does: "Stores time-bucketed traffic metrics.",
    outputs: "Historical patterns (e.g. Tuesday 08:40 average flow)",
    why: "Predictions compare live traffic with historical patterns.",
    simple: "Time-based traffic data.",
    technical:
      "Hypertables with continuous aggregates (1 min / 15 min / hourly) for counts, speeds and occupancy per approach.",
  },
  postgis: {
    id: "postgis",
    name: "Geospatial Road Graph",
    tech: "PostGIS",
    layer: "storage",
    receives: "Camera locations, road segments, junctions",
    does: "Models the city as a graph with distances and allowed movements.",
    outputs: "Upstream/downstream relationships, travel distances",
    why: "MAARG must know which camera feeds which signal, and how far apart they are.",
    simple: "Geospatial road and camera relationships.",
    technical:
      "Road segments as LineStrings, cameras/junctions as Points; topology queries return the upstream cameras of a junction approach and segment lengths for ETA estimation.",
  },
  association: {
    id: "association",
    name: "Multi-Camera Association",
    tech: "Python · rules + similarity scoring",
    layer: "cloud",
    receives: "Observations from different cameras",
    does: "Decides which observations belong to the same vehicle journey.",
    outputs: "Linked observation chain (journey ID)",
    why: "Local edge track IDs only exist inside one camera.",
    simple: "Recognises the same vehicle seen by different cameras.",
    technical:
      "Candidate pairs are filtered by road-graph connectivity and feasible travel time, then scored on plate match, vehicle type, direction and speed consistency.",
  },
  trajectory: {
    id: "trajectory",
    name: "Trajectory Reconstruction",
    tech: "Python · PostGIS",
    layer: "cloud",
    receives: "Linked observation chain",
    does: "Rebuilds the route between cameras along the road graph.",
    outputs: "Journey path, segment travel times",
    why: "Travel times between cameras reveal real congestion and feed predictions.",
    simple: "Draws the path the vehicle actually took.",
    technical:
      "Shortest feasible path on the road graph between consecutive detections; segment travel times update live speed estimates.",
  },
  analytics: {
    id: "analytics",
    name: "Traffic Analytics",
    tech: "Stream processing",
    layer: "cloud",
    receives: "Observations + trajectories",
    does: "Computes counts, density, speed, queue length and occupancy per approach.",
    outputs: "Live metrics per junction",
    why: "These are the inputs of every signal decision.",
    simple: "Turns records into traffic numbers.",
    technical: "Sliding-window aggregations (e.g. 30 s / 5 min) per lane and approach, written to Redis and TimescaleDB.",
  },
  prediction: {
    id: "prediction",
    name: "Prediction Engine",
    tech: "Decision logic / prediction engine",
    layer: "cloud",
    receives: "Upstream counts, speeds, distances, queues, history",
    does: "Estimates how many vehicles reach each junction and when.",
    outputs: "Predicted arrivals (e.g. 37 vehicles at J-04 in 20 s)",
    why: "Signals can prepare for traffic before it arrives.",
    simple: "Predicts how much traffic is about to arrive.",
    technical:
      "Arrival estimates combine upstream platoon size, segment distance and live speed (ETA = distance ÷ speed) adjusted with historical profiles. Shown here as a conceptual simulation.",
  },
  optimizer: {
    id: "optimizer",
    name: "Signal Optimisation Engine",
    tech: "Decision logic",
    layer: "cloud",
    receives: "Predicted arrivals + current signal state + constraints",
    does: "Calculates green extensions/reductions within safety limits.",
    outputs: "Timing plan (e.g. extend NS green +18 s)",
    why: "Turns predictions into actual signal timing.",
    simple: "Decides how long each light should stay green.",
    technical:
      "Evaluates candidate timings against min/max green, pedestrian clearance, maximum red wait for cross streets and downstream spillback, then selects the plan with the lowest expected delay.",
  },
  alerts: {
    id: "alerts",
    name: "Alert Engine",
    tech: "Rules engine",
    layer: "cloud",
    receives: "Live metrics + vehicle events",
    does: "Raises alerts for congestion, emergency vehicles and anomalies.",
    outputs: "Alerts to operators and corridor manager",
    why: "Operators need to be told when something unusual happens.",
    simple: "Raises a flag when something needs attention.",
    technical: "Threshold and pattern rules over the live metric stream; emergency class detections trigger the corridor workflow.",
  },
  controller: {
    id: "controller",
    name: "Signal Controller",
    tech: "Junction controller interface",
    layer: "control",
    receives: "Timing plan from MAARG",
    does: "Applies phase changes on the physical signal with interlock safety.",
    outputs: "Signal phases (green / yellow / red)",
    why: "This is where the decision becomes action on the road.",
    simple: "The box that actually switches the lights.",
    technical:
      "The local controller keeps conflict-monitor safety (no conflicting greens, fixed yellow and all-red clearance) and accepts timing adjustments from MAARG; it falls back to its local plan if communication is lost.",
  },
};

export const SAMPLE_OBSERVATION = {
  camera_id: "CAM_07",
  timestamp: "08:42:16",
  vehicle_id: "V1042",
  plate: "DL01AB1234",
  vehicle_type: "car",
  lane: 2,
  direction: "north",
  speed: 42,
  latitude: 30.7046,
  longitude: 76.7179,
  confidence: 0.96,
};

export type TraceStage = {
  id: string;
  label: string;
  techId: string;
  zone: "Road" | "Edge" | "Stream" | "Cloud" | "Storage" | "Control";
  entered: string;
  processing: string;
  left: string;
};

export const TRACE_STAGES: TraceStage[] = [
  {
    id: "cam",
    label: "CAM_07",
    techId: "camera",
    zone: "Road",
    entered: "Light from the road: a white car in lane 2, northbound.",
    processing: "Camera sensor captures 25 frames per second and encodes them as H.264 video.",
    left: "RTSP video stream · ~4 Mbit/s · stays on the local network",
  },
  {
    id: "edge",
    label: "Edge Server",
    techId: "frames",
    zone: "Edge",
    entered: "RTSP video stream from CAM_07",
    processing: "OpenCV decodes the stream into frames, stamps time, applies preprocessing.",
    left: "frame #182 · 1920×1080 · ts 08:42:16.120 → resized 640×640 tensor",
  },
  {
    id: "yolo",
    label: "YOLO",
    techId: "yolo",
    zone: "Edge",
    entered: "Preprocessed frame tensor (640×640)",
    processing: "Object detector finds vehicles and classifies them.",
    left: '{ box: [812,402,1104,640], class: "car", score: 0.94 }',
  },
  {
    id: "bytetrack",
    label: "ByteTrack",
    techId: "bytetrack",
    zone: "Edge",
    entered: "Detections from frames 182, 183, 184 …",
    processing: "Links boxes across frames into one track; estimates lane, direction and speed.",
    left: '{ track_id: 1042, lane: 2, direction: "north", speed_kmh: 42 }',
  },
  {
    id: "ocr",
    label: "PaddleOCR",
    techId: "ocr",
    zone: "Edge",
    entered: "Best plate crop from track 1042",
    processing: "Reads characters, validates Indian plate format, fuses multiple frames.",
    left: '{ plate: "DL01AB1234", ocr_conf: 0.96 }',
  },
  {
    id: "obs",
    label: "Observation",
    techId: "observation",
    zone: "Edge",
    entered: "Track 1042 + plate + camera metadata",
    processing: "Builds one schema-validated event when the track crosses the count line.",
    left: '{ camera_id: "CAM_07", vehicle_id: "V1042", plate: "DL01AB1234", … } · ~0.5 KB',
  },
  {
    id: "kafka",
    label: "Kafka",
    techId: "kafka",
    zone: "Stream",
    entered: "Observation OBS-10421 from edge producer EDGE_J01",
    processing: "Appended to topic maarg.observations, partition 3, offset 884213.",
    left: "Event delivered to cloud consumer groups (ingestion, analytics, alerts)",
  },
  {
    id: "cloud",
    label: "MAARG Cloud",
    techId: "ingestion",
    zone: "Cloud",
    entered: "Raw observation event",
    processing: "Schema validation, de-duplication, enrichment with road segment S-118.",
    left: '{ …observation, segment: "S-118", junction_next: "J-04" }',
  },
  {
    id: "store",
    label: "MongoDB / TimescaleDB",
    techId: "mongodb",
    zone: "Storage",
    entered: "Enriched observation",
    processing: "Stored as a document (MongoDB); lane counts aggregated into 1-min buckets (TimescaleDB).",
    left: "Observation stored · flow(J-04 N, 08:42) = 38 veh/min",
  },
  {
    id: "postgis",
    label: "PostGIS",
    techId: "postgis",
    zone: "Storage",
    entered: 'Query: "Where does CAM_07 lead?"',
    processing: "Road-graph lookup of the downstream junction and distance.",
    left: "CAM_07 → J-04 northern approach · 180 m",
  },
  {
    id: "trajectory",
    label: "Trajectory Engine",
    techId: "trajectory",
    zone: "Cloud",
    entered: "DL01AB1234 seen at CAM_01 (08:41:18) and CAM_07 (08:42:16)",
    processing: "Associates observations and reconstructs the path on the road graph.",
    left: "Journey JRN-5531: CAM_01 → J-02 → CAM_07 · 500 m in 58 s ≈ 31 km/h",
  },
  {
    id: "predict",
    label: "Traffic Prediction",
    techId: "prediction",
    zone: "Cloud",
    entered: "42 vehicles upstream at CAM_07, 180 m away, 36 km/h",
    processing: "ETA = 180 m ÷ 10 m/s ≈ 18 s; compared with J-04 signal state.",
    left: "Prediction: 42 vehicles reach J-04 in ~18 s (NS green ends in 18 s)",
  },
  {
    id: "optimize",
    label: "Signal Optimisation",
    techId: "optimizer",
    zone: "Cloud",
    entered: "Prediction + J-04 state + constraints (max green 60 s, EW wait cap)",
    processing: "Checks downstream capacity and cross-street wait, selects lowest-delay plan.",
    left: 'Plan: { junction: "J-04", phase: "NS", green: 30 → 48 s }',
  },
  {
    id: "light",
    label: "Traffic Light",
    techId: "controller",
    zone: "Control",
    entered: "Timing plan for J-04",
    processing: "Controller applies the extension while keeping yellow and all-red clearance.",
    left: "J-04 NS GREEN extended to 48 s · platoon passes without stopping",
  },
];

export const NAV_SECTIONS = [
  { id: "overview", label: "Live pipeline", n: "00" },
  { id: "camera", label: "Camera capture", n: "01" },
  { id: "edge", label: "Edge AI server", n: "02" },
  { id: "packet", label: "Edge → Cloud packet", n: "03" },
  { id: "kafka", label: "Real-time streaming", n: "04" },
  { id: "cloud", label: "MAARG cloud", n: "05" },
  { id: "storage", label: "Database layer", n: "06" },
  { id: "association", label: "Multi-camera association", n: "07" },
  { id: "gis", label: "GIS road graph", n: "08" },
  { id: "intelligence", label: "Traffic intelligence", n: "09" },
  { id: "signal", label: "Dynamic signal timing", n: "10" },
  { id: "compare", label: "Fixed vs MAARG", n: "11" },
  { id: "modes", label: "Control modes", n: "12" },
  { id: "emergency", label: "Emergency corridor", n: "13" },
  { id: "vip", label: "VIP movement", n: "14" },
  { id: "edge-vs-cloud", label: "Edge vs Cloud", n: "15" },
  { id: "final", label: "From video to decision", n: "16" },
] as const;
